<?php
/** @var \ZooShopCatalog\Product\Create\CreateForm $createForm */
$createForm = $this->createForm;
?>
<?=$this->form()->openTag($createForm); ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $createForm->getTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $createForm->getOriginalTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/select', [
    'formElement' => $createForm->getCategory()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/select', [
    'formElement' => $createForm->getBrands()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $createForm->getSku()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $createForm->getSlug()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/textarea', [
    'formElement' => $createForm->getDescription()
]) ?>


<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $createForm->getMetaTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/textarea', [
    'formElement' => $createForm->getMetaDescription()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $createForm->getMetaKeywords()
]) ?>

<?=$this->formInput($createForm->getCsrf()) ?>
<?=$this->formButton($createForm->getSubmit(), $createForm->getSubmitValue()) ?>
<?=$this->form()->closeTag(); ?>