<?php
/** @var \ZooShopCatalog\Product\Edit\EditForm $editForm */
$editForm = $this->editForm;
?>
<?=$this->form()->openTag($editForm); ?>
<div class="form-group row">
    <?=$this->formLabel($editForm->getTitle())?>
    <div class="col-sm-8">
        <?=$this->formInput($editForm->getTitle())?>
    </div>
    <?=$this->formElementErrors($editForm->getTitle()) ?>
</div>
<div class="form-group row">
    <?=$this->formLabel($editForm->getCategory())?>
    <div class="col-sm-8">
        <?=$this->formSelect($editForm->getCategory())?>
    </div>
    <?=$this->formElementErrors()->setMessageOpenFormat('<div class="alert alert-warning" style="width: 100%;" role="alert">')
        ->setMessageSeparatorString('</div><div class="alert alert-warning" style="width: 100%;" role="alert">')
        ->setMessageCloseString('</div>')
        ->render($editForm->getCategory()) ?>
</div>
<?=$this->formInput($editForm->getCsrf()) ?>
<?=$this->formButton($editForm->getSubmit(), $editForm->getSubmitValue()) ?>
<?=$this->form()->closeTag(); ?>