<?php
/** @var \ZooShopCatalog\Product\Edit\EditForm $editForm */
$editForm = $this->editForm;
?>
<?=$this->form()->openTag($editForm); ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
        'formElement' => $editForm->getTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/select', [
        'formElement' => $editForm->getCategory()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/select', [
        'formElement' => $editForm->getBrands()
]) ?>
<?=$this->formInput($editForm->getCsrf()) ?>
<?=$this->formButton($editForm->getSubmit(), $editForm->getSubmitValue()) ?>
<?=$this->form()->closeTag(); ?>