<?php
/** @var \ZooShopCatalog\Product\Edit\EditForm $editForm */
$editForm = $this->editForm;
?>
<?=$this->form()->openTag($editForm); ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
        'formElement' => $editForm->getTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $editForm->getOriginalTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/select', [
        'formElement' => $editForm->getCategory()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/select', [
        'formElement' => $editForm->getBrands()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $editForm->getSku()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $editForm->getSlug()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/textarea', [
    'formElement' => $editForm->getDescription()
]) ?>

<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $editForm->getMetaTitle()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/textarea', [
    'formElement' => $editForm->getMetaDescription()
]) ?>
<?=$this->partial('zoo-shop-app::partial/form/input-text', [
    'formElement' => $editForm->getMetaKeywords()
]) ?>

<?=$this->formInput($editForm->getCsrf()) ?>
<?=$this->formButton($editForm->getSubmit(), $editForm->getSubmitValue()) ?>
<?=$this->form()->closeTag(); ?>